version: '3'
services:
  SD-FLASHCARD:
    container_name: SD Flash Card
    image: docker.corp.jabil.org/automation-bel/flashcard:latest
    volumes: 
      - /media/pi/boot/:/sd/media/pi/boot/
      - /dev/sdb:/sd/dev/sdb

    privileged: true
    tty: true
    dns_search: corp.jabil.org