version: '3'
services:
  SD-FLASHCARD:
    container_name: flashcard
    image: docker.corp.jabil.org/automation-bel/flashcard:latest
    volumes: 
      - /run/dbus:/host/run/dbus
      - /proc/sysrq-trigger:/aio/sysrq
      - /storage/pi/:/storage/pi/:z
      
      - /media/pi/boot/:/sd/media/pi/boot/
      - /dev/sdb:/sd/dev/sdb
    ports:
      - "8080:5900"
    privileged: true
    tty: true
    dns_search: corp.jabil.org