# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\software_SD_Card.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1361, 772)
        MainWindow.setStyleSheet("background-color:#cccccc;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1381, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.container_logo = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.container_logo.setContentsMargins(0, 0, 0, 0)
        self.container_logo.setObjectName("container_logo")
        self.header = QtWidgets.QWidget(self.gridLayoutWidget_2)
        self.header.setStyleSheet("background-color:rgb(0,123,255);")
        self.header.setObjectName("header")
        self.logo = QtWidgets.QLabel(self.header)
        self.logo.setGeometry(QtCore.QRect(30, 0, 131, 91))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:/Users/2334487/Downloads/logo_sd.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.header)
        self.label.setGeometry(QtCore.QRect(1160, -30, 171, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\JabilLogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.container_logo.addWidget(self.header, 1, 0, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, 80, 1361, 691))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.container_body = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.container_body.setContentsMargins(15, 12, 15, 12)
        self.container_body.setObjectName("container_body")
        self.widget = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget.setStyleSheet("background-color:#ededed;\n"
"border:2px solid;\n"
"border-radius:16px;\n"
"border-color:transparent;\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1331, 101))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.container_text = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.container_text.setContentsMargins(0, 0, 0, 0)
        self.container_text.setObjectName("container_text")
        self.label_instruction = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_instruction.setMinimumSize(QtCore.QSize(900, 70))
        self.label_instruction.setMaximumSize(QtCore.QSize(900, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_instruction.setFont(font)
        self.label_instruction.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_instruction.setAcceptDrops(False)
        self.label_instruction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_instruction.setAutoFillBackground(False)
        self.label_instruction.setAlignment(QtCore.Qt.AlignCenter)
        self.label_instruction.setWordWrap(True)
        self.label_instruction.setObjectName("label_instruction")
        self.container_text.addWidget(self.label_instruction, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 500, 1331, 161))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.container_buttons = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.container_buttons.setContentsMargins(0, 0, 0, 0)
        self.container_buttons.setHorizontalSpacing(100)
        self.container_buttons.setObjectName("container_buttons")
        self.button_start = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.button_start.setMinimumSize(QtCore.QSize(320, 0))
        self.button_start.setMaximumSize(QtCore.QSize(320, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.button_start.setFont(font)
        self.button_start.setStyleSheet("background-color:rgb(0,123,255);\n"
"color:#FFFFFF;\n"
"border:2px solid;\n"
"border-radius:16px;\n"
"border-color:transparent;\n"
"")
        self.button_start.setText("DOWNLOAD")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\download-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_start.setIcon(icon)
        self.button_start.setIconSize(QtCore.QSize(60, 60))
        self.button_start.setObjectName("button_start")
        self.container_buttons.addWidget(self.button_start, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.container_buttons.addItem(spacerItem, 0, 0, 1, 1)
        self.button_confirm = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.button_confirm.setMinimumSize(QtCore.QSize(166, 0))
        self.button_confirm.setMaximumSize(QtCore.QSize(166, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button_confirm.setFont(font)
        self.button_confirm.setStyleSheet("background-color:#77bf9f;\n"
"color:#FFFFFF;\n"
"border:2px solid;\n"
"border-radius:16px;\n"
"border-color:transparent;\n"
"")
        self.button_confirm.setObjectName("button_confirm")
        self.container_buttons.addWidget(self.button_confirm, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.pushButton_2.setMinimumSize(QtCore.QSize(166, 80))
        self.pushButton_2.setMaximumSize(QtCore.QSize(166, 80))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:#bf7777;\n"
"color:#FFFFFF;\n"
"border:2px solid;\n"
"border-radius:16px;\n"
"border-color:transparent;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.container_buttons.addWidget(self.pushButton_2, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.container_buttons.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(-1, 100, 1331, 401))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_gif = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_gif.setMaximumSize(QtCore.QSize(361, 371))
        self.label_gif.setStyleSheet("")
        self.label_gif.setText("")
        self.label_gif.setPixmap(QtGui.QPixmap(".\\instruction_sd.gif"))
        self.label_gif.setScaledContents(True)
        self.label_gif.setObjectName("label_gif")
        self.gridLayout.addWidget(self.label_gif, 0, 0, 1, 1)
        self.label_infos = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_infos.sizePolicy().hasHeightForWidth())
        self.label_infos.setSizePolicy(sizePolicy)
        self.label_infos.setMinimumSize(QtCore.QSize(500, 200))
        self.label_infos.setMaximumSize(QtCore.QSize(500, 200))
        self.label_infos.setStyleSheet("background-color:#FFFFFF;\n"
"border:1px solid;\n"
"border-radius:16px;\n"
"border-color:#000000;\n"
"")
        self.label_infos.setText("")
        self.label_infos.setObjectName("label_infos")
        self.gridLayout.addWidget(self.label_infos, 0, 1, 1, 1)
        self.container_body.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_instruction.setText(_translate("MainWindow", "INSIRA O CARTÃO E PRESSIONE O BOTÃO  PARA INICIAR O DOWNLOAD"))
        self.button_confirm.setText(_translate("MainWindow", "CONFIRM"))
        self.pushButton_2.setText(_translate("MainWindow", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
