version: '2'
services:
  # All in One appication
  AIO:
    image: docker.corp.jabil.org/automation-bel/aio:latest
    volumes:
      - /run/dbus:/host/run/dbus
      - /proc/sysrq-trigger:/aio/sysrq
      - /storage/pi/:/storage/pi/:z
    ports:
      - "8080:5900"
    privileged: true
    hostname: raspberrypi
    tty: true
    dns_search: corp.jabil.org
